name: multi_trigger_autocomplete
homepage: https://github.com/xsahil03x/multi_trigger_autocomplete
description: A flutter widget to add trigger based autocomplete functionality to your app.
version: 0.1.1
repository: https://github.com/xsahil03x/multi_trigger_autocomplete
issue_tracker: https://github.com/xsahil03x/multi_trigger_autocomplete/issues

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_portal: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0